author: J. Morgan Lieberthal
github_url: https://github.com/baberthal/RingBuffer
github_file_prefix: https://github.com/baberthal/RingBuffer/tree/master

theme: fullwidth
clean: true
min_acl: internal

skip_undocumented: false
hide_documentation_coverage: false
